### ISSUE TITLE
Additional type class to simplify exposed API and signatures

### ISSUE THREAD

**Issue by paluh** [mbuszka/purescript-record-recursion-schemes#6]
I've on this branch commit which introduces additional type class to simplify library API and signatures so we can drop `RowToList` constraint and `RLProxy` passing in our helpers:

https://github.com/paluh/purescript-record-fold/commit/17ab29e04b884b00446bfba0419b58b88b1b2b58

What do you think? Should I provide a PR with this change?

**Comment by paluh** [comment]
I've also added type class which further simplifies `FoldMap` signatures on this branch (I'm using it in `length` and `labels` functions):

https://github.com/paluh/purescript-record-fold/blob/954705c66bc40af44e547833f1921f5db7866c37/src/Data/Record/Fold.purs#L80

If you want incorporate these changes too. Please ignore my PR and will provide new single one.

**Comment by paluh** [comment]
There is also funny variations which optimizes `labels` a bit (could be even done in "safe unsafe way" to optimize it further by mutating accumulator):

https://github.com/paluh/purescript-record-fold/blob/endo-variations/src/Data/Record/Fold.purs#L96

Unfortunately it brings a lot of garbage too (we can drop `Endo` and use `Join` from purescript-profunctors, but it is quite heavy dependency).

**Comment by paluh** [comment]
Ingore above comment - if we want to make it efficient we can probably use `Array.ST` ;-)

**Comment by mbuszka** [comment]
I like the Fold typeclass, which indeed cleans up API.
